#! /usr/bin/env ruby

require "bundler"

Bundler.require

require_relative "cli"

Cli.run do |params|
  cooking = Cooking.new(params[:noodles])

  cooking.hourglasses << params[:hourglass1]
  cooking.hourglasses << params[:hourglass2]

  unless cooking.valid?
    cooking.errors.each { puts _1 }

    exit 3
  end

  time = cooking.time_total

  if time.zero?
    puts "You can't cook this noodles with these hourglasses."
  else
    puts "Total cooking time: #{cooking.time_total.to_i} minutes"
  end
end
